var range = 
[["Dairy",["Dead", "Big", "force one cow to make the milk for three", "spend thousands developing cheese"]], 
["Chemicals",["Alive", "Big", "use chemicals and start WWIII", "React more Sodium and Chloride for the saltiest nation alive"]], 
["Airplanes", ["Dead", "Big", "find two new buildings"]],
["Crops", ["Alive", "Big", "develop 400 tons of harmful pesticides"]],
["Banking", ["Alive", "Big", "mislead the nation, and start a second Great Depression"],
["Computers", ["Alive", "Big", ""]],
["Books", ["Dead", "Big", ""]],
["Education", ["Alive", "Big", ""]],
["Energy",["Alive", "Big", ""]],
["Fashion",["Alive", "Big", ""]],
["Beverages",["Alive", "Big", ""]],
["Health", ["Alive", "Big", ""]],
["Insurance", ["Alive", "Big", ""]],
["Legality", ["Alive", "Big", ""]],
["Manafacturing", ["Alive", "Big", ""]],
["Media", ["Alive", "Big", ""]],
["Music", ["Alive", "Big", ""]],
["Tourism", ["Alive", "Big", ""]],
["Cars", ["Alive", "Big", ""]],
["Steel", ["Alive", "Big", ""]],
["Oil", ["Alive", "Big", ""]],
["Gold", ["Alive", "Big", ""]],
["Video Games", ["Alive", "Big", "brainwash a generation of killers", ""]],
["Phones", ["Alive", "Big", ""]],
["Boats", ["Alive", "Big", ""]],
["Fishing", ["Alive", "Big", ""]],
["Stationery", ["Alive", "Big", ""]],
["Junk Food", ["Alive", "Big", ""]]
}